export const PASSWORD_SECRET = process.env["PASSWORD_SECRET"];

export const PASSWORD_RESET_SECRET = process.env["PASSWORD_RESET_SECRET"];

export const EMAIL_VERIFICATION_SECRET =
  process.env["EMAIL_VERIFICATION_SECRET"];

export const EMAIL_NOREPLY_PASSWORD = process.env["EMAIL_NOREPLY_PASSWORD"];
