name: Deploy to Remote Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile

      - name: Build Application
        env:
          VITE_PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}
          VITE_PASSWORD_RESET_SECRET: ${{ secrets.PASSWORD_RESET_SECRET }}
          VITE_EMAIL_VERIFICATION_SECRET: ${{ secrets.EMAIL_VERIFICATION_SECRET }}
          VITE_EMAIL_NOREPLY_PASSWORD: ${{ secrets.EMAIL_NOREPLY_PASSWORD }}
          VITE_EMAIL_ICLOUD_USER: ${{ secrets.EMAIL_ICLOUD_USER }}
          VITE_EMAIL_ICLOUD_PASSWORD: ${{ secrets.EMAIL_ICLOUD_PASSWORD }}
        run: yarn build

      - name: Save SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST}} >> ~/.ssh/known_hosts

      - name: Copy Build to Remote Server
        run: rsync -a --delete build prisma package.json yarn.lock ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:helvetikon

      - name: Install Production Dependencies | Remote
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd helvetikon && yarn install --prod"

      - name: Migrate Database & Restart Server | Remote
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd helvetikon && npx prisma migrate deploy && pm2 reload helvetikon && pm2 reload helvetikon-prisma"
