name: Deploy to Remote Server

on:
  push:
    branches: [master, dockerization]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile

      - name: Build Application
        env:
          VITE_PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}
          VITE_PASSWORD_RESET_SECRET: ${{ secrets.PASSWORD_RESET_SECRET }}
          VITE_EMAIL_VERIFICATION_SECRET: ${{ secrets.EMAIL_VERIFICATION_SECRET }}
          VITE_EMAIL_NOREPLY_PASSWORD: ${{ secrets.EMAIL_NOREPLY_PASSWORD }}
          VITE_EMAIL_ICLOUD_USER: ${{ secrets.EMAIL_ICLOUD_USER }}
          VITE_EMAIL_ICLOUD_PASSWORD: ${{ secrets.EMAIL_ICLOUD_PASSWORD }}
        run: yarn build
      
      - name: Pull Repository and Rebuild Containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd helvetikon
            git pull
            docker compose up --build -d