name: Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - run: |
        yarn install --frozen-lockfile
        yarn build
