name: Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: |
        yarn install --frozen-lockfile
        yarn build
