name: SSH Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envKey_VITE_JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - run: yarn build
      - name: Save SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST}} >> ~/.ssh/known_hosts
      - name: Copy Build to Remote Server
        run: rsync -a --delete --exclude '.env' --exclude 'node_modules' build prisma package.json yarn.lock ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:test
      - name: Start the server
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd test && yarn install --prod"
      - name: Migrate database
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd test && prisma migrate deploy"
