name: Publish Docker image and deploy to server

on:
  push:
    branches: [master]

jobs:
  publish_image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: noahsalvi/helvetikon

  deploy:
    needs: publish_image
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: SSH run deployment instructions
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd helvetikon
            git pull --ff-only
            docker compose pull
            docker compose down
            docker volume rm helvetikon_app
            docker compose up -d --remove-orphans
            docker image prune -f
